version: '3.8'

services:
  notifications:
    build:
      context: ./notifications
    container_name: nauman919_notifications
    ports:
      - "8001:9000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=pgsql://postgres:adminadmin@postgres:5432/symfony_notifications?serverVersion=16&charset=utf8
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages

  users:
    build:
      context: ./users
    container_name: nauman919_users
    ports:
      - "8000:9000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=pgsql://postgres:adminadmin@postgres:5432/symfony_users?serverVersion=16&charset=utf8
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nauman919_rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"

  postgres:
    image: postgres:14
    container_name: nauman919_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: symfony_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
