version: '3.8'

services:
  notifications:
    build:
      context: ./notifications
    container_name: nauman919_notifications
    ports:
      - "8001:9000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:adminadmin@postgres:5432/nauman919_notifications_db?serverVersion=14&charset=utf8
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
    command: |
      bash -c "sleep 10 &&
              php bin/console doctrine:database:create &&
               php bin/console doctrine:migrations:migrate &&
               php -S 0.0.0.0:9000 -t public"
    networks:
      - nauman919_network

  users:
    build:
      context: ./users
    container_name: nauman919_users
    ports:
      - "8000:9000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:adminadmin@postgres:5432/nauman919_users_db?serverVersion=14&charset=utf8
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
    command: |
      bash -c "sleep 10 &&
              php bin/console doctrine:database:create &&
               php bin/console doctrine:migrations:migrate &&
               php bin/console doctrine:database:create --env=test &&
               php bin/console doctrine:migrations:migrate --env=test &&
               php -S 0.0.0.0:9000 -t public"
    networks:
      - nauman919_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nauman919_rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - nauman919_network

  postgres:
    image: postgres:14
    container_name: nauman919_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: symfony_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
    networks:
      - nauman919_network

networks:
  nauman919_network:
    driver: bridge
